name       : vimix-gtk-theme
version    : '20220424'
release    : 6
source     :
    - https://github.com/vinceliuice/vimix-gtk-themes/archive/refs/tags/2022-04-24.tar.gz : 5ce0200148fe7f85a38ef147918677db22496253a603d7eb9ca00f0265c2c2a1
homepage   : https://github.com/vinceliuice/vimix-gtk-themes
license    : GPL-3.0-only
component  : desktop.theme
summary    : Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell.
builddeps  :
    - gnome-shell
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes -n Vimix -a -s standard compact
    rm -rf $installdir/usr/share/themes/Vimix*/{cinnamon,unity,xfwm4}
    rm -f $installdir/usr/share/themes/*/{AUTHORS,LICENSE}
