name       : vimix-gtk-theme
version    : '20200224'
release    : 1
source     :
    - https://github.com/vinceliuice/vimix-gtk-themes/archive/2020-02-24.tar.gz : 5630d7bfb09820978459b2ce2f7db6cacbb2a34a4c8f73ca3b706301310927bd
license    : GPL-3.0-only
component  : desktop.theme
summary    : Vimix is a flat Material Design theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments.
rundeps    :
    - gtk2-engine-murrine
    - gtk-engines
description: |
    Vimix is a flat Material Design theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments like Gnome, Unity, Budgie, Pantheon, XFCE, Mate, etc.
install    : |
    install -dm00755 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes -n Vimix
    rm -rf $installdir/usr/share/themes/Vimix*/{cinnamon,unity,xfwm4}
