name       : vimix-gtk-theme
version    : '20230621'
release    : 9
source     :
    - https://github.com/vinceliuice/vimix-gtk-themes/archive/refs/tags/2023-06-21.tar.gz : 4a90c68ba2ac263bb3e7d82014e8257e4ffb36b5bf58158ecfb88fe7d50db94c
homepage   : https://github.com/vinceliuice/vimix-gtk-themes
license    : GPL-3.0-only
component  : desktop.theme
summary    : Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell.
builddeps  :
    - gnome-shell
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes -n Vimix -t all -s all
    rm -rf $installdir/usr/share/themes/Vimix*/{cinnamon,unity,xfwm4}
    rm -f $installdir/usr/share/themes/*/{AUTHORS,LICENSE}
