name       : vimix-gtk-theme
version    : '20210425'
release    : 3
source     :
    - https://github.com/vinceliuice/vimix-gtk-themes/archive/refs/tags/2021-04-25.tar.gz : 709cff4100fd0ddc762ae7ece648a45b49281c607876db77121a67a3a8fecb56
homepage   : https://github.com/vinceliuice/vimix-gtk-themes
license    : GPL-3.0-only
component  : desktop.theme
summary    : Vimix is a flat Material Design theme for GTK, GTK-based desktop environments, and GNOME Shell
description: |
    Vimix is a flat Material Design theme for GTK, GTK-based desktop environments, and GNOME Shell.
builddeps  :
    - gnome-shell
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes -n Vimix -a
    rm -rf $installdir/usr/share/themes/Vimix*/{cinnamon,unity,xfwm4}
    rm -f $installdir/usr/share/themes/*/{AUTHORS,LICENSE}
