name       : vimix-gtk-theme
version    : '20221030'
release    : 7
source     :
    - https://github.com/vinceliuice/vimix-gtk-themes/archive/refs/tags/2022-10-30.tar.gz : 42253bb970852ee9fb0ae3d425134091acf12c4435485d0cbcd4537bec359388
homepage   : https://github.com/vinceliuice/vimix-gtk-themes
license    : GPL-3.0-only
component  : desktop.theme
summary    : Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell.
builddeps  :
    - gnome-shell
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes -n Vimix -a -s standard compact
    rm -rf $installdir/usr/share/themes/Vimix*/{cinnamon,unity,xfwm4}
    rm -f $installdir/usr/share/themes/*/{AUTHORS,LICENSE}
