name       : vimix-gtk-theme
version    : '20201128'
release    : 2
source     :
    - https://github.com/vinceliuice/vimix-gtk-themes/archive/2020-11-28.tar.gz : c2fbe0d29cb32ab4b4cd4f419655212c684bb1cb9becd37eb6b7874f5555fc8d
license    : GPL-3.0-only
component  : desktop.theme
summary    : Vimix is a flat Material Design theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments.
rundeps    :
    - gtk2-engine-murrine
    - gtk-engines
description: |
    Vimix is a flat Material Design theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments like Gnome, Unity, Budgie, Pantheon, XFCE, Mate, etc.
install    : |
    install -dm00755 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes -n Vimix -a
    rm -rf $installdir/usr/share/themes/Vimix*/{cinnamon,unity,xfwm4}
    rm -f $installdir/usr/share/themes/*/{AUTHORS,LICENSE}
