name       : vimix-gtk-theme
version    : '20210817'
release    : 5
source     :
    - https://github.com/vinceliuice/vimix-gtk-themes/archive/refs/tags/2021-08-17.tar.gz : 5f34c86ec23c5d826ee79db68a38bb2f6a970ed865ebe81e5dc09df7fa506444
homepage   : https://github.com/vinceliuice/vimix-gtk-themes
license    : GPL-3.0-only
component  : desktop.theme
summary    : Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes -n Vimix -a
    rm -rf $installdir/usr/share/themes/Vimix*/{cinnamon,unity,xfwm4}
    rm -f $installdir/usr/share/themes/*/{AUTHORS,LICENSE}
